### ISSUE TITLE
Cannot add multiple switches to same dashboard

### ISSUE THREAD

**Issue by wspek** [wspek/grafana-switch-panel#4]
In GitLab by @wspek on Apr 27, 2019, 12:58

**Comment by wspek** [comment]
Also, when you switch from Switch to 3DGauge and back again, you get the same error.

`"[DEFAULT]: Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app).
    at er (http://localhost:3000/public/plugins/grafana-switch-panel/external/firebase.js:1:39918)
    at Object.initializeApp (http://localhost:3000/public/plugins/grafana-switch-panel/external/firebase.js:1:41616)
    at Database.init (http://localhost:3000/public/plugins/grafana-switch-panel/database.js:31:16)
    at jQuerySwitchCtrl (http://localhost:3000/public/plugins/grafana-switch-panel/ctrl.js:59:14)
    at Object.invoke (http://localhost:3000/public/build/vendor.dc8293754b17a74e301b.js:67183:19)
    at $controllerInit (http://localhost:3000/public/build/vendor.dc8293754b17a74e301b.js:73143:34)
    at nodeLinkFn (http://localhost:3000/public/build/vendor.dc8293754b17a74e301b.js:71995:36)
    at compositeLinkFn (http://localhost:3000/public/build/vendor.dc8293754b17a74e301b.js:71317:13)
    at publicLinkFn (http://localhost:3000/public/build/vendor.dc8293754b17a74e301b.js:71182:30)
    at appendAndCompile (http://localhost:3000/public/build/app.dc8293754b17a74e301b.js:44529:24)"`

**Comment by wspek** [comment]
created branch [`4-cannot-add-multiple-switches-to-same-dashboard`](https://gitlab.com/gentile-spek/grafana-switch-panel/compare/develop...4-cannot-add-multiple-switches-to-same-dashboard) to address this issue

**Comment by wspek** [comment]
- Multiple switches adopt the same custom colours. This should be fixed.
- Perhaps the whole document paradigm should be rethought. https://cloud.google.com/community/tutorials/cloud-iot-firestore-config

**Comment by wspek** [comment]
closed via merge request !5

**Comment by wspek** [comment]
mentioned in commit 4c4249233dacb1454d0179ad5f2f8c1154f9c0fc
